church_of_jowett/container/src/routes.py
from flask import (
    request,
    jsonify,
    Blueprint,
    current_app,
    make_response,
    render_template,
    redirect,
    url_for,
)
from src.auth import (
    decode_token,
    requires_pope,
    requires_token,
    is_authenticated,
    token_value,
    requires_cardinal,
    is_cardinal_role,
    is_pope_role,
)
import random

api = Blueprint("api", __name__)


@api.route("/")
def index():
    if is_pope_role() and is_cardinal_role():
        return render_template(
            "public.html", is_auth=True, is_cardinal_role=True, is_pope_role=True
        )
    elif is_cardinal_role():
        return render_template("public.html", is_auth=True, is_cardinal_role=True)
    elif is_authenticated():
        return render_template("public.html", is_auth=True)
    return render_template("public.html")


@api.route("/signup", methods=("POST", "GET"))
def signup():

    # make sure user isn't authenticated
    if is_pope_role() and is_cardinal_role():
        return render_template(
            "public.html", is_auth=True, is_cardinal_role=True, is_pope_role=True
        )
    elif is_cardinal_role():
        return render_template("public.html", is_auth=True, is_cardinal_role=True)
    elif is_authenticated():
        return render_template("public.html", is_auth=True)

    # get form data
    if request.method == "POST":
        jwt_data = {}
        jwt_data["name"] = request.form.get("name")
        jwt_data["email"] = request.form.get("email")
        jwt_data["is_cardinal"] = False
        jwt_data["is_pope"] = False
        jwt_cookie = current_app.auth.create_token(jwt_data)
        if is_cardinal_role():
            response = make_response(
                redirect(
                    url_for(
                        "api.index",
                        is_auth=True,
                        is_cardinal_role=True,
                        is_pope_role=False,
                    )
                )
            )
        else:
            response = make_response(redirect(url_for("api.index", is_auth=True)))

        response.set_cookie("auth_token", jwt_cookie, httponly=True)
        return response

    return render_template("signup.html")


@api.route("/promote", methods=("GET", "POST"))
@requires_token
def promote():
    if is_pope_role() and is_cardinal_role():
        return render_template(
            "public.html", is_auth=True, is_cardinal_role=True, is_pope_role=True
        )
    elif is_cardinal_role():
        return render_template("public.html", is_auth=True, is_cardinal_role=True)
    elif request.method == "POST":
        jwt_cookie = promote_token()
        response = make_response(
            redirect(
                url_for(
                    "api.index", is_auth=True, is_cardinal_role=True, is_pope_role=False
                )
            )
        )
        response.set_cookie("auth_token", jwt_cookie, httponly=True)
        return response
    return render_template("promote.html")


@api.route("/cardinal_revelations", methods=("GET",))
@requires_cardinal
def cardinal_win():
    if is_pope_role() and is_cardinal_role():
        return render_template(
            "cardinal_revelations.html",
            flag="saint{v4l1d4t1ng_s3cr3ts_1s_f0r_chumps}",
            is_auth=True,
            is_cardinal_role=True,
            is_pope_role=True,
        )
    else:
        return render_template(
            "cardinal_revelations.html",
            flag="saint{v4l1d4t1ng_s3cr3ts_1s_f0r_chumps}",
            is_auth=True,
            is_cardinal_role=True,
        )


@api.route("/profile", methods=("GET",))
@requires_token
def info():
    data = decode_token(request.cookies.get("auth_token"))
    if is_pope_role() and is_cardinal_role():
        return render_template(
            "info.html",
            name=data["name"],
            email=data["email"],
            is_auth=True,
            is_cardinal_role=True,
            is_pope_role=True,
        )
    elif is_cardinal_role():
        return render_template(
            "info.html",
            name=data["name"],
            email=data["email"],
            is_auth=True,
            is_cardinal_role=True,
        )
    else:
        return render_template(
            "info.html", name=data["name"], email=data["email"], is_auth=True
        )


@api.route("/todo_list", methods=("GET",))
@requires_cardinal
def todo():
    if is_pope_role:
        return render_template(
            "todo.html",
            is_auth=True,
            is_cardinal_role=True,
            is_pope_role=True,
        )
    else:
        return render_template(
            "todo.html",
            is_auth=True,
            is_cardinal_role=True,
        )


@api.route("/pope_revelations", methods=("GET",))
@requires_pope
def pope_win():
    return render_template(
        "pope_revelations.html",
        flag="saint{h1_j0w3tt_y0u_r3411y_4r3_th3_b3st}",
        is_auth=True,
        is_cardinal_role=True,
        is_pope_role=True,
    )


@api.route("/logout")
def logout():
    response = make_response(redirect(url_for("api.index")))
    response.delete_cookie("auth_token")
    return response

church_of_jowett/container/src/templates/base.html
<!DOCTYPE html>
<!-- this is used as the base holding the navbar and bootstrap screw with this and I'll kill you -->

<style>
    .right-item {
        list-style-type: none;
    }

    html, body {
        margin: 0px;
        padding: 0px;
        background-color: #751a27;
        font-family: 'Comic Sans MS', 'Comic Sans', cursive !important;
    }

</style>

<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <title>The Holy church of Jowett</title>
    <base href="/">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootswatch/4.3.1/lux/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-hVpXlpdRmJ+uXGwD5W6HZMnR9ENcKVRn855pPbuI/mwPIEKAuKgTKgGksVGmlAvt" crossorigin="anonymous">

</head>
<body>
<app-root></app-root>
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>

<nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #a6192e;">
    <a class="navbar-brand" href="/">Church of Jowett</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01"
            aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav ml-md-auto d-block d-sm-flex d-md-flex">
            {% if is_auth == true %}
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('api.pope_win') }}">Revelations for the Pope</a>
            </li>

                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('api.cardinal_win') }}">Revelations for Cardinals</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('api.todo') }}">To do list</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('api.info') }}">Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('api.logout') }}">Logout</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('api.signup') }}">Sign Up</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>
<article id="container" style="background-color: #751a27;">
    <!-- Om nom nom me love cookies https://jwt.io/ -->
    {% block body %}
        // Content will be here
    {% endblock %}
</article>
</body>
</html>

church_of_jowett/container/src/templates/cardinal_revelations.html
{% extends 'base.html' %}
{% block body %}

    <style>
        .top {
            top: 0;
            text-align: center;
            padding-left:  30px;
            padding-top: 40px;
            padding-bottom: 30px;
            padding-right:  30px;
        }

        .h1 {
            font-size: 60px;
            margin-bottom: 60px;
        }

        .user_info {
            font-size:18px;
            padding-left: 17px;
            color: white;
        }

        .table {
            color: white;
            table-layout: fixed;
            width: 100%;
        }

    </style>

    <div class="top">
        <h4 style="margin-bottom:20px; color:white">Revelations for Cardinals:</h4>
        <table class="table">
            <thead style="background-color: #a6192e;  color: white;">
                <tr>
                    <th scope="col" width="15%">Revelation</th>
                    <th scope="col">Content</th>
                </tr>
            </thead>
            <tbody style="background-color: #7a1010;">
                <tr>
                    <td>Flag</td>
                    <td>{{ flag }}</td>
                </tr>
                <tr>
                    <td>SCSA</td>
                    <td>SCSA does their job properly, and the comp sci curse is well put together</td>
                </tr>
                <tr>
                    <td>Part 2</td>
                    <td>The pope also has a flag, but their authentication is more secure</td>
                </tr>
            </tbody>
        </table>
    </div>

{% endblock %}

church_of_jowett/container/src/templates/info.html
{% extends 'base.html' %}
{% block body %}

    <style>
        .top {
            top: 0;
            text-align: center;
            padding-left:  30px;
            padding-top: 40px;
            padding-bottom: 30px;
            padding-right:  30px;
        }

        .h1 {
            font-size: 50px;
        }

        .user_info {
            font-size:18px;
            padding-left: 17px;
            color: white;
        }

        .table {
            color: white;
            table-layout: fixed;
            width: 100%;
        }

    </style>

    <div class="top">
        <h1 style="margin-bottom:10%; color:white">Hello, {{ name }}.</h4>
        <h2 style="color: white;">Your email is: {{ email }}<br>Your rank is: {% if is_pope_role %}The pope!<br>May Jowett bestow wisdom and power upon you.{% elif is_cardinal_role == true %} Graced cardinal of the Holy Church of Jowett. {% else %} Good priest of the Holy Church of Jowett {% endif%} </p>

{% endblock %}

church_of_jowett/container/src/templates/pope_revelations.html
{% extends 'base.html' %}
{% block body %}

    <style>
        .top {
            top: 0;
            text-align: center;
            padding-left:  30px;
            padding-top: 40px;
            padding-bottom: 30px;
            padding-right:  30px;
        }

        .h1 {
            font-size: 60px;
            margin-bottom: 60px;
        }

        .user_info {
            font-size:18px;
            padding-left: 17px;
            color: white;
        }

        .table {
            color: white;
            table-layout: fixed;
            width: 100%;
        }

    </style>

    <div class="top">
        <h4 style="margin-bottom:20px; color:white">Revelations for the Pope:</h4>
        <table class="table">
            <thead style="background-color: #a6192e; color: white;">
                <tr>
                    <th scope="col" width="15%">Revelation</th>
                    <th scope="col">Content</th>
                </tr>
            </thead>
            <tbody style="background-color: #7a1010;">
                <tr>
                    <td>Flag</td>
                    <td>{{ flag }}</td>
                </tr>
                <tr>
                    <td>Driving</td>
                    <td>Handbrake turns around tight corners at high speed are a great way to impress new colleagues and intimidate rivals</td>
                </tr>
                <tr>
                    <td>SCSA</td>
                    <td>SCSA does their job properly, and the comp sci curse is well put together</td>
                </tr>
            </tbody>
        </table>
    </div>

{% endblock %}

church_of_jowett/container/src/templates/public.html
{% extends 'base.html' %}
{% block body %}

    <style>
        .top {
            top: 0;
            text-align: center;
            padding-top: 40px;
            padding-bottom: 70px
        }

        .h1 {
            font-size: 60px;
            margin-bottom: 60px;
            color: white;
        }

    </style>

    <div class="top">
        <h1 class="h1">Welcome to the Holy Church of Jowett</h1>
        <img src="/jowett.jpg" height="580" width="800">
    </div>

{% endblock %}

church_of_jowett/container/src/templates/signup.html
{% extends 'base.html' %}
{% block body %}

    <style>
        .text-center {
            width: 30%;
            text-align: center;
            margin-top: 20px;
            margin-left: auto;
            margin-right: auto;
        }

        .text-center a {
            font-family: Trebuchet MS Serif;
            font-color: blue;
            margin-top: 10px;
        }

        .top {
            top: 0;
            text-align: center;
            background-color: #7a1010;
            padding-top: 50px;
            padding-bottom: 40px;
        }

        .hl {
            font-size: 50px;
            color: white;
        }

        .bottom {
            margin-bottom: 20px;
        }

    </style>

    <div class="top">
        <h1 class="hl">Sign up</h1>
    </div>

    <div class="text-center">
        <form class="form-login" method="post">
            <fieldset>
                <legend style="margin-bottom: 20px">Create a new account to join the church:</legend>

                <div class="form-group">
                    <label for="Username" class="spacing">Enter your Name:</label>
                    <input type="text" class="form-control" id="name" name="name" placeHolder="Name"

                           required autofocus>
                </div>

                <div class="form-group">
                    <label for="Email" class="spacing">Enter your Email:</label>
                    <input type="email" class="form-control" id="email" name="email" placeHolder="Email" required

                           autofocus>
                </div>

                <div class="form-group">
                    <label for="Password" class="spacing">Enter a password:</label>
                    <input type="password" class="form-control" id="password" name="password" placeHolder="Password"

                           required autofocus>
                </div>

                <button type="submit" class="btn btn-primary" style="margin-bottom: 20px">Submit</button>

            </fieldset>
        </form>
    </div>

{% endblock %}

church_of_jowett/container/src/templates/todo.html
{% extends 'base.html' %}
{% block body %}

    <style>
        .top {
            top: 0;
            text-align: center;
            padding-left:  30px;
            padding-top: 40px;
            padding-bottom: 30px;
            padding-right:  30px;
        }

        .h1 {
            font-size: 60px;
            margin-bottom: 60px;
        }

        .user_info {
            font-size:18px;
            padding-left: 17px;
            color: black;
        }

        .table {
            color: white;
            table-layout: fixed;
            width: 40%;
            margin-left: auto;
            margin-right: auto;
            background-color: #7a1010;
            border: 3px solid #a6192e;
        }

    </style>

    <div class="top">
        <h4 style="margin-bottom:100px; color:white">Official agenda of the holy church of Jowett</h4>
        <table class="table">
            <tbody>
                <tr>
                    <td>Change the JWT secret from "jowett_is_the_best"</td>
                </tr>
                <tr>
                    <td>Convert Michael Morgan to the Holy Church of Jowett</td>
                </tr>
                <tr>
                    <td>Become the official religion of Shenton College</td>
                </tr>
            </tbody>
        </table>
    </div>

{% endblock %}